version: '3'
services:
    chatbot_casamento:
        image: python:3.7.3
        volumes:
            - '.:/usr/src/app'
        networks:
            - proxy_net
            - chatbot_net
        working_dir: /usr/src/app
        command: bash -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    db:
      image: postgres:11
      restart: always
      environment:
        POSTGRES_USER: chatbotuser
        POSTGRES_PASSWORD: chatbotpss
        POSTGRES_DB: chatbotdb
      networks:
        - chatbot_net
networks:
    chatbot_net:
      driver: bridge
    proxy_net:
      external: true
